# Generated by Django 5.1.6 on 2025-02-19 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_student_gender_alter_student_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='reg_num',
            field=models.PositiveIntegerField(default=1000, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], default='Male', max_length=10),
        ),
    ]
