# Generated by Django 5.1.6 on 2025-02-19 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_alter_student_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='reg_num',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
    ]
