# Generated by Django 5.1.6 on 2025-02-19 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_alter_student_reg_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='reg_num',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True, unique=True),
        ),
    ]
